### ISSUE TITLE
Love this!

### ISSUE THREAD

**Issue by trix1210** [BrijeshPaghdal/EasyGift#1]
Hi Brijesh!

I've been working on your easygift project for the last few weeks as I really like it and Id like to give you back the files with the code I have changed!

Ive got the product filter working very well and made loads of other enhancements!

The only problem is I have no idea how to use github except to download the repos!

If you can tell me how to give you the files that ive improved, It would be great!

many thanks
Alex.
LONDON,UK

**Comment by BrijeshPaghdal** [comment]
you can fork the project and then apply your changes and generate the pull request i will check it and apply it in my code
